require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PropagationsController do

  # This should return the minimal set of attributes required to create a valid
  # Propagation. As you add validations to Propagation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "trade" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PropagationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all propagations as @propagations" do
      propagation = Propagation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:propagations).should eq([propagation])
    end
  end

  describe "GET show" do
    it "assigns the requested propagation as @propagation" do
      propagation = Propagation.create! valid_attributes
      get :show, {:id => propagation.to_param}, valid_session
      assigns(:propagation).should eq(propagation)
    end
  end

  describe "GET new" do
    it "assigns a new propagation as @propagation" do
      get :new, {}, valid_session
      assigns(:propagation).should be_a_new(Propagation)
    end
  end

  describe "GET edit" do
    it "assigns the requested propagation as @propagation" do
      propagation = Propagation.create! valid_attributes
      get :edit, {:id => propagation.to_param}, valid_session
      assigns(:propagation).should eq(propagation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Propagation" do
        expect {
          post :create, {:propagation => valid_attributes}, valid_session
        }.to change(Propagation, :count).by(1)
      end

      it "assigns a newly created propagation as @propagation" do
        post :create, {:propagation => valid_attributes}, valid_session
        assigns(:propagation).should be_a(Propagation)
        assigns(:propagation).should be_persisted
      end

      it "redirects to the created propagation" do
        post :create, {:propagation => valid_attributes}, valid_session
        response.should redirect_to(Propagation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved propagation as @propagation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propagation.any_instance.stub(:save).and_return(false)
        post :create, {:propagation => { "trade" => "invalid value" }}, valid_session
        assigns(:propagation).should be_a_new(Propagation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propagation.any_instance.stub(:save).and_return(false)
        post :create, {:propagation => { "trade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested propagation" do
        propagation = Propagation.create! valid_attributes
        # Assuming there are no other propagations in the database, this
        # specifies that the Propagation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Propagation.any_instance.should_receive(:update).with({ "trade" => "" })
        put :update, {:id => propagation.to_param, :propagation => { "trade" => "" }}, valid_session
      end

      it "assigns the requested propagation as @propagation" do
        propagation = Propagation.create! valid_attributes
        put :update, {:id => propagation.to_param, :propagation => valid_attributes}, valid_session
        assigns(:propagation).should eq(propagation)
      end

      it "redirects to the propagation" do
        propagation = Propagation.create! valid_attributes
        put :update, {:id => propagation.to_param, :propagation => valid_attributes}, valid_session
        response.should redirect_to(propagation)
      end
    end

    describe "with invalid params" do
      it "assigns the propagation as @propagation" do
        propagation = Propagation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propagation.any_instance.stub(:save).and_return(false)
        put :update, {:id => propagation.to_param, :propagation => { "trade" => "invalid value" }}, valid_session
        assigns(:propagation).should eq(propagation)
      end

      it "re-renders the 'edit' template" do
        propagation = Propagation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propagation.any_instance.stub(:save).and_return(false)
        put :update, {:id => propagation.to_param, :propagation => { "trade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested propagation" do
      propagation = Propagation.create! valid_attributes
      expect {
        delete :destroy, {:id => propagation.to_param}, valid_session
      }.to change(Propagation, :count).by(-1)
    end

    it "redirects to the propagations list" do
      propagation = Propagation.create! valid_attributes
      delete :destroy, {:id => propagation.to_param}, valid_session
      response.should redirect_to(propagations_url)
    end
  end

end
